# Generated by Django 4.2.7 on 2024-03-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercises_templates_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='templates_folder_name',
            field=models.CharField(default='in-develop-templates', max_length=20, verbose_name='Папка шаблонов'),
        ),
    ]
