# Generated by Django 4.2.7 on 2024-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exercises_templates_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'тексты',
                'db_table': 'texts',
            },
        ),
    ]
